apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    component: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
 ---
kind: PersistentVolume  # Create a PV
apiVersion: v1
metadata:
  name: postgres-pv-volume    # Sets PV's name
  labels:
    type: local   # Sets PV's type to local
    component: postgres
spec:
  storageClassName: manual
  capacity:
    storage:  1Gi  # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mtd/data"  # Sets the volume's path
 
