pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/k8s-frontend-backend-deployment']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sandeep-1511/lms-private.git']]])
            }
        }
        stage('docker build') {
            steps { 
                script {
                    sh 'cd api && docker build -t sandeeppunna/lms-public-api .'
                }
            }   
        }
        stage('docker login') {
            steps { 
                script {
                    withCredentials([string(credentialsId: 'sandeeppunna', variable: 'dockerhubid')]) {
                    sh 'docker login -u sandeeppunna -p ${dockerhubid}'      
                        
}
   
                    sh 'docker push sandeeppunna/lms-public-api'
                    sh 'docker image rmi -f sandeeppunna/lms-public-api'
                }    
            }
        }
        stage('kubernetes deploy') {
            steps { 
                script {
                    echo 'Deploying....'
                    sh " cd k8s && kubectl apply -f postgres-deployment.yaml "
                    sh " cd k8s && kubectl apply -f database-persistent-volume-claim.yaml "
                   // sh " cd k8s && kubectl apply -f api-deployment.yaml "
                    //sh " cd k8s && kubectl apply -f postgres-cluster-ip-service.yaml "
                    //sh " cd k8s && kubectl apply -f api-load-balancer-service.yaml "
                    //sh " kubectl rollout restart deployment/postgres-deployment "
                    //sh " kubectl rollout restart deployment/api-deployment "
                }
            }                    
        }
    }
}
